// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in ent-validation-bug/ent/runtime.go

const (
	Version = "v0.9.2-0.20210903142140-c511be69b68b"            // Version of ent codegen.
	Sum     = "h1:RsR8sHv/v3EsA8DkjxYIJCduj5F+a66GWnU63eN9vWk=" // Sum of ent codegen.
)
