// Code generated by entc, DO NOT EDIT.

package ent

import (
	"ent-validation-bug/ent/schema"
	"ent-validation-bug/ent/work"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	workFields := schema.Work{}.Fields()
	_ = workFields
	// workDescName is the schema descriptor for name field.
	workDescName := workFields[0].Descriptor()
	// work.NameValidator is a validator for the "name" field. It is called by the builders before save.
	work.NameValidator = workDescName.Validators[0].(func(string) error)
}
